"""
Functions and global constant state
(as in geographical US state) information
"""

from typing import Optional
from locations import Location

STATES = [Location('AK', 'Alaska', ()),
          Location('AL', 'Alabama', ()),
          Location('AR', 'Arkansas', ()),
          Location('AZ', 'Arizona', ()),
          Location('CA', 'California', ()),
          Location('CO', 'Colorado', ()),
          Location('CT', 'Connecticut', ()),
          Location('DC', 'District of Columbia', ('Washington DC',)),
          Location('DE', 'Delaware', ()),
          Location('FL', 'Florida', ()),
          Location('GA', 'Georgia', ()),
          Location('HI', 'Hawaii', ()),
          Location('IA', 'Iowa', ()),
          Location('ID', 'Idaho', ()),
          Location('IL', 'Illinois', ()),
          Location('IN', 'Indiana', ()),
          Location('KS', 'Kansas', ()),
          Location('KY', 'Kentucky', ()),
          Location('LA', 'Louisiana', ()),
          Location('MA', 'Massachusetts', ()),
          Location('MD', 'Maryland', ()),
          Location('ME', 'Maine', ()),
          Location('MI', 'Michigan', ()),
          Location('MN', 'Minnesota', ()),
          Location('MO', 'Missouri', ()),
          Location('MS', 'Mississippi', ()),
          Location('MT', 'Montana', ()),
          Location('NC', 'North Carolina', ()),
          Location('ND', 'North Dakota', ()),
          Location('NE', 'Nebraska', ()),
          Location('NH', 'New Hampshire', ()),
          Location('NJ', 'New Jersey', ()),
          Location('NM', 'New Mexico', ()),
          Location('NV', 'Nevada', ()),
          Location('NY', 'New York', ()),
          Location('OH', 'Ohio', ()),
          Location('OK', 'Oklahoma', ()),
          Location('OR', 'Oregon', ()),
          Location('PA', 'Pennsylvania', ()),
          Location('PR', 'Puerto Rico', ()),
          Location('RI', 'Rhode Island', ()),
          Location('SC', 'South Carolina', ()),
          Location('SD', 'South Dakota', ()),
          Location('TN', 'Tennessee', ()),
          Location('TX', 'Texas', ()),
          Location('UT', 'Utah', ()),
          Location('VA', 'Virginia', ()),
          Location('VT', 'Vermont', ()),
          Location('WA', 'Washington', ()),
          Location('WI', 'Wisconsin', ()),
          Location('WV', 'West Virginia', ()),
          Location('WY', 'Wyoming', ())]
